# Generated by Django 5.2.5 on 2025-10-03 16:51

import django.core.validators
import django.db.models.deletion
import jobs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Education Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_board_license', models.BooleanField(default=False, help_text='True for PRC Board Licenses, False for Civil Service')),
            ],
            options={
                'verbose_name_plural': 'Eligibility Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='jobs.educationcategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='jobs.eligibilitycategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Position Title')),
                ('place_of_assignment', models.CharField(max_length=300)),
                ('plantilla_item_no', models.CharField(blank=True, max_length=50)),
                ('salary_job_grade', models.CharField(blank=True, max_length=10)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('permanent', 'Permanent'), ('casual', 'Casual'), ('contractual', 'Contractual'), ('coterminous', 'Coterminous')], default='permanent', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('education_requirement', models.TextField(help_text="e.g., Bachelor's Degree relevant to the job")),
                ('training_requirement', models.CharField(help_text='e.g., 16 hours of relevant training', max_length=200)),
                ('experience_requirement', models.CharField(help_text='e.g., 3 years of relevant experience', max_length=200)),
                ('eligibility_requirement', models.TextField(help_text='e.g., Career Service Professional / Second Level Eligibility OR Board License')),
                ('competency_requirement', models.TextField(blank=True, help_text='Optional preferred qualifications')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Posting Date')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField(verbose_name='Closing Date')),
                ('education_levels', models.ManyToManyField(blank=True, related_name='jobs', to='jobs.educationlevel')),
                ('eligibility_types', models.ManyToManyField(blank=True, help_text='Can include Civil Service AND/OR Board Licenses', related_name='jobs', to='jobs.eligibilitytype')),
                ('posted_by', models.ForeignKey(limit_choices_to={'user_type': 'hr'}, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_of_intent', models.TextField(help_text='Indicate position, item number, and place of assignment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='HR notes', null=True)),
                ('screening_score', models.IntegerField(blank=True, help_text='Automated screening score 0-100', null=True)),
                ('screening_result', models.CharField(blank=True, choices=[('highly_qualified', 'Highly Qualified'), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified')], max_length=50, null=True)),
                ('screening_details', models.JSONField(blank=True, help_text='Detailed screening breakdown', null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(limit_choices_to={'user_type': 'applicant'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('letter_of_intent', 'Letter of Intent'), ('pds', 'Personal Data Sheet (CS Form 212)'), ('wes', 'Work Experience Sheet'), ('performance_rating', 'Performance Rating (if applicable)'), ('eligibility_license', 'Eligibility Certificate / Board License'), ('transcript', 'Transcript of Records'), ('training_certificates', 'Training Certificates'), ('other', 'Other Supporting Documents')], max_length=30)),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=jobs.models.get_document_upload_path, validators=[jobs.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('ocr_processed', models.BooleanField(default=False)),
                ('ocr_data', models.JSONField(blank=True, null=True)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('ocr_error', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='jobs.application')),
            ],
            options={
                'ordering': ['document_type', '-uploaded_at'],
                'indexes': [models.Index(fields=['application', 'document_type'], name='jobs_applic_applica_39a13b_idx'), models.Index(fields=['document_type', 'ocr_processed'], name='jobs_applic_documen_6bc1ad_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-created_at'], name='jobs_job_status_57b86b_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['deadline'], name='jobs_job_deadlin_c19edf_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='jobs_applic_job_id_a25382_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', '-applied_at'], name='jobs_applic_applica_f72c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['screening_result'], name='jobs_applic_screeni_1189c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'applicant')},
        ),
    ]
