# Generated by Django 5.2.5 on 2025-10-06 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='letter_of_intent',
        ),
        migrations.AddField(
            model_name='application',
            name='application_letter',
            field=models.FileField(blank=True, null=True, upload_to='application_letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='document_type',
            field=models.CharField(choices=[('application_letter', 'Application Letter'), ('pds', 'Personal Data Sheet (CS Form 212)'), ('wes', 'Work Experience Sheet'), ('performance_rating', 'Performance Rating (if applicable)'), ('eligibility_license', 'Eligibility Certificate / Board License'), ('transcript', 'Transcript of Records'), ('training_certificates', 'Training Certificates'), ('other', 'Other Supporting Documents')], max_length=30),
        ),
    ]
