# Generated by Django 5.2.5 on 2025-10-02 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobposting_created_by_job_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Education Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Eligibility Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='jobs.educationcategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='education_levels',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.educationlevel'),
        ),
        migrations.CreateModel(
            name='EligibilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='jobs.eligibilitycategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='eligibility_types',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.eligibilitytype'),
        ),
    ]
