# Generated by Django 5.2.5 on 2025-10-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_application_letter_of_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='was_closed',
            field=models.BooleanField(default=False, help_text='Tracks if job was reopened after being closed'),
        ),
    ]
