# Generated by Django 5.2.5 on 2025-10-02 18:11

import django.core.validators
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_educationcategory_eligibilitycategory_job_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='certificates',
            field=models.FileField(blank=True, help_text='Certificates (PDF or ZIP/RAR archive, Max 10MB)', null=True, upload_to=jobs.models.certificates_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'rar'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='pds',
            field=models.FileField(blank=True, help_text='Personal Data Sheet (Max 5MB)', null=True, upload_to=jobs.models.pds_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(help_text='Accepted formats: PDF, DOC, DOCX (Max 5MB)', upload_to=jobs.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
